name: CI

on:
  pull_request:
    branches: ["main"]
    paths:
      - ".github/workflows/ci.yml"
      - "lib/**"
      - "plugins/**"
      - "tests/**"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run ShellCheck
        uses: azohra/shell-linter@latest
        with:
          path: "lib/*.sh,plugins/*.sh"
          exclude-paths: ".github,LICENSE,README.md,version.txt"

  version-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check if version has to be changed
        id: version-check
        shell: bash
        run: |
          git diff-index --name-only --diff-filter=d origin/main | grep -q -i "^lib\/" && echo "lib folder has changes"
          git diff-index --name-only --diff-filter=d origin/main | grep -q "^plugins\/" && echo "plugins folder has changes"
          
          if git diff-index --name-only --diff-filter=d origin/main | grep -q -i "^lib\/" || \
            git diff-index --name-only --diff-filter=d origin/main | grep -q "^plugins\/" ; then
            echo "version has to change"
            if git diff-index --name-only --diff-filter=d origin/main | grep -q "version.txt"; then
              echo "version.txt file has been modified"
            else
              echo "ERROR: version.txt file has not been modified, probably you should update it"
              exit 1
            fi
          fi

      - id: get-version
        run: echo "::set-output name=version::$(cat version.txt)"

      - id: semver
        uses: matt-usurp/validate-semver@v1
        with:
          version: ${{ steps.get-version.outputs.version }}
      
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Bash Unit Tests
        env:
          DEFAULT_PATH: "${{ github.workspace }}/tests/unit"
        run: |
          "${{ github.workspace }}/tests/lib/bashunit"
